# Generated by Django 2.2.6 on 2020-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0003_auto_20200213_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalDetails', models.CharField(max_length=40)),
                ('dateToAchieveBy', models.DateTimeField(verbose_name='Start Date')),
            ],
        ),
    ]
