# Generated by Django 2.2.6 on 2020-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0004_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='dateToAchieveBy',
            field=models.DateTimeField(verbose_name='Date to achieve by'),
        ),
    ]
