# Generated by Django 3.0.4 on 2020-04-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0008_auto_20200219_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='isGoalChecked',
            field=models.BooleanField(default=False),
        ),
    ]
