# Generated by Django 3.0.4 on 2020-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0010_event_ticketcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
