# Generated by Django 3.0.4 on 2020-04-12 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0011_auto_20200412_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts',
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
