# Generated by Django 3.0.4 on 2020-04-12 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0012_auto_20200412_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
