# Generated by Django 3.0.4 on 2020-04-12 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0013_auto_20200412_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 12, 17, 30, 40, 632511, tzinfo=utc), verbose_name='Start Time'),
        ),
    ]
