# Generated by Django 3.0.4 on 2020-04-12 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0014_auto_20200412_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 12, 17, 31, 39, 989652, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 12, 17, 31, 39, 989652, tzinfo=utc), verbose_name='Start Time'),
        ),
    ]
