# Generated by Django 3.0.4 on 2020-04-13 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0017_auto_20200413_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 13, 16, 3, 10, 949339, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventDescription',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventGenre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventHost',
            field=models.CharField(default='Saagar Shah', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventLocation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 13, 16, 3, 10, 949339, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalDetails',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trick',
            name='difficultyLevel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trick',
            name='propCategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trick',
            name='trickDescription',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='trick',
            name='trickName',
            field=models.CharField(max_length=200),
        ),
    ]
