# Generated by Django 3.0.4 on 2020-04-13 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0018_auto_20200413_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 13, 16, 14, 28, 586969, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventLocation',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 13, 16, 14, 28, 586969, tzinfo=utc), verbose_name='Start Time'),
        ),
    ]
