# Generated by Django 3.0.4 on 2020-04-13 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0019_auto_20200413_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 13, 16, 33, 28, 364521, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 13, 16, 33, 28, 364521, tzinfo=utc), verbose_name='Start Time'),
        ),
    ]
