# Generated by Django 3.0.4 on 2020-04-14 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0020_auto_20200413_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forumContributorName', models.CharField(max_length=100)),
                ('forumPostTitle', models.CharField(max_length=200)),
                ('forumComment', models.CharField(max_length=400)),
                ('forumOptionalMedia', models.ImageField(blank=True, upload_to='forum_media')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 19, 3, 31, 73250, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventHost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 14, 19, 3, 31, 73250, tzinfo=utc), verbose_name='Start Time'),
        ),
    ]
