# Generated by Django 3.0.4 on 2020-04-16 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0028_auto_20200416_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumresponse',
            name='forumPostID',
            field=models.IntegerField(default=37),
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 16, 22, 26, 32, 134416, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 16, 22, 26, 32, 133416, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='timePostSubmitted',
            field=models.TimeField(default=datetime.datetime(2020, 4, 16, 22, 26, 32, 134416, tzinfo=utc), verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='forumresponse',
            name='timeResponded',
            field=models.TimeField(default=datetime.datetime(2020, 4, 16, 22, 26, 32, 135415, tzinfo=utc), verbose_name='Response Time'),
        ),
    ]
