# Generated by Django 3.0.7 on 2020-07-05 00:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0043_auto_20200704_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='belongsToWhichUser',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Juggleology.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 15, 13, 799550, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 15, 13, 799479, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='timePostSubmitted',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 15, 13, 800138, tzinfo=utc), verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='forumresponse',
            name='timeResponded',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 15, 13, 800896, tzinfo=utc), verbose_name='Response Time'),
        ),
    ]
