# Generated by Django 3.0.7 on 2020-07-05 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0044_auto_20200705_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trick',
            name='belongsToWhichUser',
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 17, 37, 589513, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 17, 37, 589476, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='timePostSubmitted',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 17, 37, 590067, tzinfo=utc), verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='forumresponse',
            name='timeResponded',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 17, 37, 590720, tzinfo=utc), verbose_name='Response Time'),
        ),
    ]
