# Generated by Django 3.0.7 on 2020-07-05 00:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0045_auto_20200705_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='belongsToWhichUser',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Juggleology.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 19, 35, 504502, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 19, 35, 504463, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='timePostSubmitted',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 19, 35, 505046, tzinfo=utc), verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='forumresponse',
            name='timeResponded',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 0, 19, 35, 505680, tzinfo=utc), verbose_name='Response Time'),
        ),
    ]
