# Generated by Django 3.0.7 on 2020-07-05 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0047_auto_20200705_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trick',
            old_name='belongsToWhichUser',
            new_name='trickBelongsToWhichUser',
        ),
        migrations.AddField(
            model_name='goal',
            name='backupUserID',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='goalBelongsToWhichUser',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='Juggleology.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 1, 17, 38, 115674, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 1, 17, 38, 115631, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='timePostSubmitted',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 1, 17, 38, 116300, tzinfo=utc), verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='forumresponse',
            name='timeResponded',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 1, 17, 38, 117037, tzinfo=utc), verbose_name='Response Time'),
        ),
    ]
