# Generated by Django 3.0.7 on 2020-07-05 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Juggleology', '0050_auto_20200705_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='backupUserID',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventBelongsToWhichUser',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='Juggleology.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 2, 2, 53, 845444, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 2, 2, 53, 845402, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='timePostSubmitted',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 2, 2, 53, 846207, tzinfo=utc), verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='forumresponse',
            name='timeResponded',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 2, 2, 53, 847250, tzinfo=utc), verbose_name='Response Time'),
        ),
    ]
